config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :movies do
    resources :reviews
    resources :ratings
  end

  root "movies#profile"
  get "/profile" => "movies#profile"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user
      can :manage,Review,user_id:user.id
      can :read,:all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :ratings,dependent: :destroy
  has_many :reviews,dependent: :destroy
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie

  after_create :update_movie_rating_average

  def update_movie_rating_average
    movie.update(average_ratings: movie.ratings.average(:rate))
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie,counter_cache: :review_count
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: :profile

  # GET /movies or /movies.json
  def profile

  end

  def index
    if params[:title]
      @movies = Movie.where("name LIKE ?", "#{params[:title]}%").order(average_ratings: :desc).includes( :reviews)
    elsif params[:start_date] && params[:end_date]
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      @movies = Movie.where(releasedate: start_date..end_date).order(average_ratings: :desc).includes( :reviews)
    else
      @movies = Movie.all.order(average_ratings: :desc).includes( :reviews)
    end

  end

  # GET /movies/1 or /movies/1.json
  def show
    @rating=@movie.ratings.new
    @reviews=@movie.reviews.all.includes(:user)
    @review=@movie.reviews.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movies_path, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :releasedate)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_movie

  def create
    @rating=@movie.ratings.new(rating_params)

    if @rating.save
      respond_to do |format|
        format.html{redirect_to movie_path(@movie),notice: @rating.save ? "rating saved successfully":"Error!while saving ratings"}
      end
    end
  end
end

private

def set_movie
  @movie=Movie.find(params[:movie_id])
end

def rating_params
  params.require(:rating).permit(:rate,:movie_id)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :set_movie


  def edit
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user=current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_path(@movie), notice: "Review was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to movie_path(@movie), notice: "Review was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to movie_path(@movie), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_movie
    @movie=Movie.find(params[:movie_id])
  end
    def set_review
      @review = Review.find(params[:id])
    end


    def review_params
      params.require(:review).permit(:comment, :movie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviereviewsystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
  <% if notice.present? %><p class="notice"><%= notice %></p><% end %>
    <% if alert.present? %> <p class="alert"><%= alert %></p><% end %>
  <% if user_signed_in? %>
  <nav class="main_nav navbar navbar-expand-lg ">
    <div class="container-fluid" >

      <p class="filter navbar-brand" >Logged in as <%= current_user.email.split('@')[0].capitalize  %></p>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav">
          <li class="nav-item">
            <p class="filter navbar-brand" ><%=link_to "Dashboard",movies_path  %></p>
          </li>
          <li class="nav-item">
            <p class=" navbar-brand" > <%= link_to "Profile",profile_path %></p>

          </li>

          <li class="nav-item">
            <p class="filter navbar-brand" style="padding-left: 65%">Movie Review System</p>
          </li>
          <li class="nav-item">
            <p class=" navbar-brand" style="padding-left: 410%"> <%= link_to "signout",destroy_user_session_path %></p>
          </li>

        </ul>
      </div>
    </div>
  </nav>
  <% end %>
  <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :releasedate %>
    <%= form.date_select :releasedate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tbody>
  <tr>
    <th>
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="filter navbar-brand">Filter by name:</a>
          <%= form_with( url: movies_path, method: :get) do |form|%>
            <%= form.text_field :title%>
            <%= form.submit "Search",class: "btn btn-outline-success" %>
          <% end %>
        </div>
      </nav>
    </th>
    <th>
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="filter navbar-brand">Filter by release_date:</a>
          <%= form_with( url: movies_path, method: :get) do|form| %>
            <%= form.label :"Start Date" %>
            <%= form.date_field :start_date%>
            <%= form.label :"End Date" %>
            <%= form.date_field :end_date%>
            <%= form.submit "Filter",class: "btn btn-outline-success"  %>
          <% end %>
        </div>
      </nav>
    </th>
  </tr>
  </tbody>
</table>

<h1>Movies</h1>

<table class="table table-success table-striped-columns">
  <thead  class="table table-dark">
    <tr>
      <th>Name</th>
      <th>Releasedate</th>
      <th>AverageRatings</th>
      <th>Reviews</th>
      <th>Create Reviews</th>
      <th>Create Ratings</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody >
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.releasedate %></td>
        <td><%= movie.average_ratings.round(1) %></td>
        <td><% if movie.review_count > 0 %>
          <% movie.reviews.each do |review|  %>
              <p><%= review.comment %> </p>
            <% end %>
            <% else %>
          <p>No Reviews</p>
            <% end %>
            </td>
        <td><%= link_to 'clickhere',movie %></td>
        <td><%= link_to 'clickhere',movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/profile.html.erb
<% if user_signed_in? %>
  <p><strong>Name:</strong>
    <%= current_user.email.split("@")[0].capitalize %></p>
  <p><strong>Email:</strong>
    <%= current_user.email %></p>
  <p> <%= link_to "signout",destroy_user_session_path %> |
    <%=link_to "Dashboard",movies_path  %> |
    <%= link_to "Edit profile", edit_user_registration_path %>
  </p>
<% else %>
  <p style="margin-top: 60px">
    <h3>Profile</h3><br><%= link_to"Signin",new_user_session_path%> |
    <%= link_to"Signup",new_user_registration_path %>
  </p>

<% end %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Releasedate:</strong>
  <%= @movie.releasedate %>
</p>
<p>
  <strong>Average Rating:</strong>
  <%= @movie.average_ratings.round(1) %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<br><hr>
<strong>Give Rating :</strong>
<%= render partial: "ratings/form",locals: { rating: @rating} %>
<hr>
<strong>Give Reviews :</strong>
<%= render partial:"reviews/form",locals: {review: @review} %>
<br>
<% if @movie.review_count> 0 %>
<strong>Existing Reviews :</strong>
  <% @reviews.each do |review| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= review.user.email.split("@")[0].capitalize%></h5>
      <p>(<%= review.user.email %>)</p>
      <strong class="card-text"><%= review.comment %></strong>
        <% if can? :update,review %>
          <%= link_to 'Edit', edit_movie_review_path(@movie,review) ,class: "btn btn-primary"%>
        <% end %>
        <% if can? :delete,review %>
          <%= link_to 'Destroy', [@movie,review] ,class: "btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
  </div>
    <% end %>
<% end %>

app/views/ratings/_form.html.erb
<%= form_with(model: [@movie,rating]) do |form| %>
  <div class="field">
    <%= form.radio_button :rate,value=1 %>
    <%= form.label :⭐ %>
  </div>
  <div class="field">
    <%= form.radio_button :rate,value=2 %>
    <%= form.label :⭐⭐ %>
  </div>

  <div class="field">
    <%= form.radio_button :rate,value=3 %>
    <%= form.label :⭐⭐⭐ %>
  </div>

  <div class="field">
    <%= form.radio_button :rate,value=4 %>
    <%= form.label :⭐⭐⭐⭐ %>
  </div>

  <div class="field">
    <%= form.radio_button :rate,value=5 %>
    <%= form.label :⭐⭐⭐⭐⭐ %>
  </div>

  <div class="actions">
    <%= form.submit "submit rating" %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: [@movie,review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>


<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.movie_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>